### ISSUE TITLE
Buttons on right side of windows lack border

### ISSUE THREAD

**Issue by tristan957** [linuxmint/mint-y-theme#17] opened 2016-06-24 21:25 UTC
For some reason buttons on the right side of some windows (About Pix window below) lack a black line border that goes all the way around the button so there isn't a definitive start to the end of the button and beginning of the window.
![screenshot from 2016-06-24 16-22-44](https://cloud.githubusercontent.com/assets/11936772/16351038/51070896-3a28-11e6-9632-5b261e6c244c.png)

**Comment by JosephMcc** [comment] 2016-06-26 08:49
I seem to remember dealing with this same issue in our Mint-X theme at one point. I don't remember the cause or the fix but I'll see if I can dig it up and get this fixed.

**Comment by JosephMcc** [comment] 2016-06-26 08:59
Ok. So I can't seem to reproduce this. Have you changed any settings by chance? Like font sizes or anything. Also make sure that when you change themes you close and reopen applications as things sometimes won't update properly until you do.

**Comment by tristan957** [comment] 2016-06-27 18:22
I changed the font to the Ubuntu Font Family. I kept all the sizes the same though. Would that cause the problem? And I made sure to restart my computer to check this.

**Comment by JosephMcc** [comment] 2016-06-27 18:34
Yep. I can reproduce the problem by doing that.

**Comment by tristan957** [comment] 2016-06-27 18:44
Cool. Is there a possible fix for it?
On Jun 27, 2016 1:34 PM, JosephMcc <notifications@github.com> wrote:Yep. I can reproduce the problem by doing that.

**Comment by JosephMcc** [comment] 2016-06-27 18:45
Not sure exactly what's going on yet. The Ubuntu font at size 9 seems to be slightly smaller than mints default font which seems to cause the issue. Changing the size to 10 sorts it out. Not a fix but a temporary workaround.

**Comment by tristan957** [comment] 2016-06-27 18:58
Do you have upstream Arc installed? Maybe you should try it on there as well
On Jun 27, 2016 1:45 PM, JosephMcc <notifications@github.com> wrote:Not sure exactly what's going on yet. The Ubuntu font at size 9 seems to be slightly smaller than mints default font which seems to cause the issue. Changing the size to 10 sorts it out. Not a fix but a temporary workaround.

**Comment by JosephMcc** [comment] 2016-06-27 19:09
I keep several themes installed for reference. This issue occurs in all of them. Some below font size 10, some 9, and all of them below 8. It seems to be some issue in Gtk.Dialog. It looks like the best I'll be able to do is make it handle 9 and possibly 8. That should be a fairly practical fix as anything below that is tiny anyway. I will close this once I make the improvements.

**Comment by tristan957** [comment] 2016-06-27 19:30
Is there a bug that either you or me could file for GTK?
On Jun 27, 2016 2:09 PM, JosephMcc <notifications@github.com> wrote:I keep several themes installed for reference. This issue occurs in all of them. Some below font size 10, some 9, and all of them below 8. It seems to be some issue in Gtk.Dialog. It looks like the best I'll be able to do is make it handle 9 and possibly 8. That should be a fairly practical fix as anything below that is tiny anyway. I will close this once I make the improvements.

**Closed** 2016-06-27 23:04 UTC
Labels: bug
