### ISSUE TITLE
Menu text scrambled

### ISSUE THREAD

**Issue by gbradf** [linuxmint/mint-y-theme#67] opened 2017-07-07 13:29 UTC
Since upgrade to 18.2 Cinnamon, text in the Menu is scrambled when Mint-y theme is applied. The glitch only occurs under sub menu's that are scrollable. 

![menu](https://user-images.githubusercontent.com/29979772/27959628-2135cdd8-6320-11e7-90c9-367dec8847f0.png)
![menu1](https://user-images.githubusercontent.com/29979772/27959630-21405ef6-6320-11e7-871f-22a071162f7b.png)
![menu3](https://user-images.githubusercontent.com/29979772/27959629-213876dc-6320-11e7-91d7-a6df79c54b07.png)

Mint 18.2 x64 Cinnamon

**Comment by JosephMcc** [comment] 2017-07-07 20:17
Someone, maybe you, reported this on one of the release blogs. We're looking into it. Not sure of the cause because I can't reproduce it here. It's possible it's related to the graphics card/driver being used. One simple workaround is to disable "Fade effects on Cinnamon scrollboxes" in System settings->Effects.

**Comment by LyckanSv** [comment] 2017-07-13 02:48
I have the same problem

**Comment by bigcat4** [comment] 2017-07-16 09:42
I can confirm that this happens on a fresh install of Mint 18.2, on a Lenovo T420 with Intel integrated graphics 3000 (driver=i915). I cannot replicate this on a Lenovo X230 for example that uses Intel integrated graphics 4000.

I can also confirm that performing your workaround suggested above does get rid of the issue - thanks!

**Comment by gbradf** [comment] 2017-07-20 18:32
Apologies for not following this up sooner. I have the same Intel integrated graphics 3000 (Lenovo X220)

**Comment by Goloka** [comment] 2017-07-23 06:12
Same as the previous ones. I do the same after upgrading to 18.2
I have a graphics card
Intel Sandybridge Mobile
And was solved with the option:
 Disable "Fade effects on Cinnamon scrollboxes"
Thanks

**Comment by smurphos** [comment] 2017-08-26 10:02
I also have this issue with Mint-Y and Mint-Y derived themes from spices - but it predates 18.2. Also Intel HD. It doesn't happen with other with other default themes or themes derived from the cinnamon base them.

```
Card: Intel 2nd Generation Core Processor Family Integrated Graphics Controller
Display Server: X.Org 1.18.4 drivers: intel (unloaded: fbdev,vesa)
Resolution: 1366x768@60.03hz
GLX Renderer: Mesa DRI Intel Sandybridge Mobile
GLX Version: 3.0 Mesa 17.0.7
```

**Comment by adilim** [comment] 2017-08-28 10:54
This is also affecting Sandy Bridge with HD Graphics 2000 CPUs

**Comment by JosephMcc** [comment] 2017-11-12 21:08
Fixed in Mint-Y by https://github.com/linuxmint/mint-y-theme/commit/45da4d3aea506a7504751cf8b5e9a536e4d45d2c

**Closed by JosephMcc** 2017-11-12 21:08 UTC
